/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.bodyMid_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.bodyTop_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.shoulder_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.arm1_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbow_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbowDeco1_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbowDeco2_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.arm2_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palm1_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.handDeco1_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palmConnector1_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palm2_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palmConnector2_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.pam3_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.index_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_2.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_2.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_2.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_2.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_2.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.middle_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_3.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_3.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_3.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_3.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_3.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.pinky_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_4.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_4.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_4.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_4.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_4.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.thumb_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.handDeco2_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.neckp1_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.neckp2_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.neckp3_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.wire2_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.wire1_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.neckBottom_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.neckTop_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.headtop_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.ear_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.headchassis_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.d2_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.d3_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.headBack_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.ear_L1_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.screenFace_maxRobot_screen_M_0.geometry} material={materials.maxRobot_screen_M} />
        <mesh geometry={nodes.screenBack_MAxRobot_screenBack_M_0.geometry} material={materials.MAxRobot_screenBack_M} />
        <mesh geometry={nodes.neutral_L_maxRobot_eyes_and_emotions_T_0.geometry} material={materials.maxRobot_eyes_and_emotions_T} />
        <mesh geometry={nodes.neutral_R_maxRobot_eyes_and_emotions_T_0.geometry} material={materials.maxRobot_eyes_and_emotions_T} />
        <mesh geometry={nodes.shoulder_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.arm1_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbow_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbowDeco1_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.elbowDeco2_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.arm2_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palm1_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.handDeco1_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palmConnector1_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palm2_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.thumb_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.handDeco2_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.palmConnector2_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.pam3_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.index_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_5.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_5.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_5.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_5.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_5.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.middle_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_6.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_6.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_6.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_6.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_6.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.pinky_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f1_Max_Robot_Fixed_T_0_7.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint1_Max_Robot_Fixed_T_0_7.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f2_Max_Robot_Fixed_T_0_7.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.joint2_Max_Robot_Fixed_T_0_7.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.f3_Max_Robot_Fixed_T_0_7.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.bodyBottom_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.hip_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.thigh_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeTop_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeOut_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeIn_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.calf_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.ankle_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.foot_R_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.hip_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.thigh_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeTop_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeOut_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.kneeIn_Max_Robot_Fixed_T_0_1.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.calf_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.ankle_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.foot_L_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.backDisk_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.chestScreen_maxRobot_screen_M_0.geometry} material={materials.maxRobot_screen_M} />
        <mesh geometry={nodes.chestScreen_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
        <mesh geometry={nodes.chestScreenBack_MAxRobot_screenBack_M_0.geometry} material={materials.MAxRobot_screenBack_M} />
        <mesh geometry={nodes.emotion_neutral_maxRobot_eyes_and_emotions_T_0.geometry} material={materials.maxRobot_eyes_and_emotions_T} />
        <mesh geometry={nodes.innerBody_Max_Robot_Fixed_T_0.geometry} material={materials.Max_Robot_Fixed_T} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
